services:
  caddy:
    container_name: caddy
    image: caddy:2.8.4
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - app-shiro
    networks:
      - app-network

  app-shiro:
    env_file:
      - .env
    container_name: mx-shiro
    image: innei/shiro:latest
    restart: "always"
    ports:
      - '2323:2323'
    depends_on:
      - app-server
    environment:
      - NEXT_SHARP_PATH=/usr/local/lib/node_modules/sharp
    networks:
      - app-network
    links:
      - app-server

  app-server:
    container_name: mx-server
    image: innei/mx-server:latest
    volumes:
      - ./data/mx-space:/root/.mx-space
    restart: "unless-stopped"
    ports:
      - "2333:2333"
    depends_on:
      - mongo
      - redis
    links:
      - mongo
      - redis
    networks:
      - app-network
    environment:
      - NODE_ENV=production
      - TZ=Asia/Shanghai
      - DB_HOST=mongo
      - REDIS_HOST=redis
      - ALLOWED_ORIGINS=localhost
      - JWT_SECRET=YOUR_SUPER_SECURED_JWT_SECRET_STRING
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:2333/info"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data/db:/data/db
    networks:
      - app-network
    restart: unless-stopped

  redis:
    image: redis
    container_name: redis
    healthcheck:
      test: ['CMD-SHELL', 'redis-cli ping | grep PONG']
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 3s
    restart: unless-stopped
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
